---
# tasks file for install_docker
---
# tasks/main.yml

- name: Install dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes